app_home:
  path: /
  controller: App\View\Home::displayHome

app_home_page:
  path: /home/{page}
  controller: App\View\Home::bookList

app_book_create:
  path: /book/create
  controller: App\View\CreateAndEdit::createBook

app_book_edit:
  path: /book/edit/{isbn}
  controller: App\View\CreateAndEdit::editBook

app_book:
  path: /book/{isbn}
  controller: App\View\Book::displayBook

app_not_found:
  path: /notfound
  controller: App\View\Home::notFound

search_autocomplete:
  path: /search/autocomplete
  controller: App\View\Search::autocomplete
  methods:    POST|HEAD

search_book:
  path: /search/book
  controller: App\View\Search::book
  methods:    POST|HEAD

ajax_ol_infos_by_isbn:
  path: /ajax/book-infos-by-isbn
  controller: App\View\OpenLibraryInfos::getBookByIsbn
  methods:    POST|HEAD

ajax_ol_infos_by_title:
  path: /ajax/book-infos-by-title
  controller: App\View\OpenLibraryInfos::getBookByTitle
  methods:    POST|HEAD

ajax_book_delete:
  path: /ajax/book-delete
  controller: App\View\CreateAndEdit::deleteBook