#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  controller: App\View\Home::displayHome

app_book:
  path: /book/{isbn}
  controller: App\View\Book::displayBook