#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  controller: App\View\Home::displayHome

app_book_create:
  path: /book/create
  controller: App\View\CreateAndEdit::createBook

app_book:
  path: /book/{isbn}
  controller: App\View\Book::displayBook

app_not_found:
  path: /notfound
  controller: App\View\Home::notFound

ajax_ol_infos_by_isbn:
  path: /ajax/book-infos-by-isbn
  controller: App\View\OpenLibraryInfos::getBookByIsbn
  methods:    POST|HEAD

ajax_ol_infos_by_title:
  path: /ajax/book-infos-by-title
  controller: App\View\OpenLibraryInfos::getBookByTitle
  methods:    POST|HEAD